// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.15.8
// source: QuoteRPC.proto

package fintech4go_pb_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestType int32

const (
	RequestType_Request_Unknown  RequestType = 0
	RequestType_Request_Snapshot RequestType = 2
	RequestType_Request_Order    RequestType = 3
)

// Enum value maps for RequestType.
var (
	RequestType_name = map[int32]string{
		0: "Request_Unknown",
		2: "Request_Snapshot",
		3: "Request_Order",
	}
	RequestType_value = map[string]int32{
		"Request_Unknown":  0,
		"Request_Snapshot": 2,
		"Request_Order":    3,
	}
)

func (x RequestType) Enum() *RequestType {
	p := new(RequestType)
	*p = x
	return p
}

func (x RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_QuoteRPC_proto_enumTypes[0].Descriptor()
}

func (RequestType) Type() protoreflect.EnumType {
	return &file_QuoteRPC_proto_enumTypes[0]
}

func (x RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestType.Descriptor instead.
func (RequestType) EnumDescriptor() ([]byte, []int) {
	return file_QuoteRPC_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_Unknown      MessageType = 0
	MessageType_ArrayMessage MessageType = 1
	MessageType_Snapshot     MessageType = 2
	MessageType_Order        MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "Unknown",
		1: "ArrayMessage",
		2: "Snapshot",
		3: "Order",
	}
	MessageType_value = map[string]int32{
		"Unknown":      0,
		"ArrayMessage": 1,
		"Snapshot":     2,
		"Order":        3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_QuoteRPC_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_QuoteRPC_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_QuoteRPC_proto_rawDescGZIP(), []int{1}
}

type QuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Types []RequestType `protobuf:"varint,1,rep,packed,name=types,proto3,enum=MDS.RPC.RequestType" json:"types,omitempty"`
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QuoteRPC_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_QuoteRPC_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_QuoteRPC_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetTypes() []RequestType {
	if x != nil {
		return x.Types
	}
	return nil
}

type QuoteDataPackage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MessageType uint32 `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Payload     []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *QuoteDataPackage) Reset() {
	*x = QuoteDataPackage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QuoteRPC_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteDataPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteDataPackage) ProtoMessage() {}

func (x *QuoteDataPackage) ProtoReflect() protoreflect.Message {
	mi := &file_QuoteRPC_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteDataPackage.ProtoReflect.Descriptor instead.
func (*QuoteDataPackage) Descriptor() ([]byte, []int) {
	return file_QuoteRPC_proto_rawDescGZIP(), []int{1}
}

func (x *QuoteDataPackage) GetMessageType() uint32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *QuoteDataPackage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type QuoteDataPackageArray struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record []*QuoteDataPackage `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
}

func (x *QuoteDataPackageArray) Reset() {
	*x = QuoteDataPackageArray{}
	if protoimpl.UnsafeEnabled {
		mi := &file_QuoteRPC_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuoteDataPackageArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteDataPackageArray) ProtoMessage() {}

func (x *QuoteDataPackageArray) ProtoReflect() protoreflect.Message {
	mi := &file_QuoteRPC_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteDataPackageArray.ProtoReflect.Descriptor instead.
func (*QuoteDataPackageArray) Descriptor() ([]byte, []int) {
	return file_QuoteRPC_proto_rawDescGZIP(), []int{2}
}

func (x *QuoteDataPackageArray) GetRecord() []*QuoteDataPackage {
	if x != nil {
		return x.Record
	}
	return nil
}

var File_QuoteRPC_proto protoreflect.FileDescriptor

var file_QuoteRPC_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x50, 0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x4d, 0x44, 0x53, 0x2e, 0x52, 0x50, 0x43, 0x22, 0x3a, 0x0a, 0x0c, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x05, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x4d, 0x44, 0x53, 0x2e, 0x52,
	0x50, 0x43, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x4f, 0x0a, 0x10, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x4a, 0x0a, 0x15, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x12,
	0x31, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x4d, 0x44, 0x53, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x2a, 0x4b, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x5f, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x10, 0x03, 0x2a,
	0x45, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x10, 0x03, 0x32, 0x96, 0x01, 0x0a, 0x0c, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x12, 0x15, 0x2e, 0x4d, 0x44, 0x53, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x4d, 0x44,
	0x53, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x30, 0x01, 0x12, 0x40, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x4d, 0x44, 0x53, 0x2e, 0x52,
	0x50, 0x43, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1e, 0x2e, 0x4d, 0x44, 0x53, 0x2e, 0x52, 0x50, 0x43, 0x2e, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x41, 0x72, 0x72, 0x61, 0x79, 0x42,
	0x13, 0x5a, 0x11, 0x66, 0x69, 0x6e, 0x74, 0x65, 0x63, 0x68, 0x34, 0x67, 0x6f, 0x2e, 0x70, 0x62,
	0x2e, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_QuoteRPC_proto_rawDescOnce sync.Once
	file_QuoteRPC_proto_rawDescData = file_QuoteRPC_proto_rawDesc
)

func file_QuoteRPC_proto_rawDescGZIP() []byte {
	file_QuoteRPC_proto_rawDescOnce.Do(func() {
		file_QuoteRPC_proto_rawDescData = protoimpl.X.CompressGZIP(file_QuoteRPC_proto_rawDescData)
	})
	return file_QuoteRPC_proto_rawDescData
}

var file_QuoteRPC_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_QuoteRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_QuoteRPC_proto_goTypes = []interface{}{
	(RequestType)(0),              // 0: MDS.RPC.RequestType
	(MessageType)(0),              // 1: MDS.RPC.MessageType
	(*QuoteRequest)(nil),          // 2: MDS.RPC.QuoteRequest
	(*QuoteDataPackage)(nil),      // 3: MDS.RPC.QuoteDataPackage
	(*QuoteDataPackageArray)(nil), // 4: MDS.RPC.QuoteDataPackageArray
}
var file_QuoteRPC_proto_depIdxs = []int32{
	0, // 0: MDS.RPC.QuoteRequest.types:type_name -> MDS.RPC.RequestType
	3, // 1: MDS.RPC.QuoteDataPackageArray.record:type_name -> MDS.RPC.QuoteDataPackage
	2, // 2: MDS.RPC.QuoteService.Subscribe:input_type -> MDS.RPC.QuoteRequest
	2, // 3: MDS.RPC.QuoteService.Request:input_type -> MDS.RPC.QuoteRequest
	4, // 4: MDS.RPC.QuoteService.Subscribe:output_type -> MDS.RPC.QuoteDataPackageArray
	4, // 5: MDS.RPC.QuoteService.Request:output_type -> MDS.RPC.QuoteDataPackageArray
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_QuoteRPC_proto_init() }
func file_QuoteRPC_proto_init() {
	if File_QuoteRPC_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_QuoteRPC_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_QuoteRPC_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteDataPackage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_QuoteRPC_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuoteDataPackageArray); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_QuoteRPC_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_QuoteRPC_proto_goTypes,
		DependencyIndexes: file_QuoteRPC_proto_depIdxs,
		EnumInfos:         file_QuoteRPC_proto_enumTypes,
		MessageInfos:      file_QuoteRPC_proto_msgTypes,
	}.Build()
	File_QuoteRPC_proto = out.File
	file_QuoteRPC_proto_rawDesc = nil
	file_QuoteRPC_proto_goTypes = nil
	file_QuoteRPC_proto_depIdxs = nil
}
